version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # we use the database folder
  db:
    build: database/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always